### ISSUE TITLE
Error message on startup of reload of Logseq

### ISSUE THREAD

**Issue by vslatten** [usoonees/logseq-plugin-paste-more#10]
I keep getting this message since 1-2 months ago. Plugin still seems to work, through.
![bilde](https://github.com/usoonees/logseq-plugin-paste-more/assets/717193/85647f3a-4a02-4fe2-ad1b-766bef23f133)

**Comment by usoonees** [comment]
@vslatten Oh, this issue should be related to the keyboard shortcut problem, and it would not impact the plugin's functionality.

Since I am unable to reproduce the issue myself, could you provide a screenshot of the error message displayed in the console log?

**Comment by vslatten** [comment]
Here you go :-)
![image](https://github.com/usoonees/logseq-plugin-paste-more/assets/717193/f0a1dd6d-6f86-4cea-988d-44e603ad8e60)

**Comment by usoonees** [comment]
<img width="972" alt="image" src="https://github.com/usoonees/logseq-plugin-paste-more/assets/56818734/89b72b31-2aae-4a85-a180-abeda407da03">
Could you show this setting? Looks like it's null, you can set to any valid keyboard shortcut.

**Comment by usoonees** [comment]
@vslatten After assigning the keyboard shortcut to '', I reproduced the error message. Since the shortcut is infrequently used, it will be removed in the upcoming update. You can upgrade to the latest version to avoid this error.

**Comment by vslatten** [comment]
Ah, I forgot I had removed the keyboard shortcut; It collided with the default shortcut for pasting text without formatting. Thanks for fixing!
