### ISSUE TITLE
开启 create a new block for new line 后，在 code block 里粘贴代码，会总是粘贴到 code block 之外

### ISSUE THREAD

**Issue by luosky** [usoonees/logseq-plugin-paste-more#11]
具体见录屏：
![20231205-113434](https://github.com/usoonees/logseq-plugin-paste-more/assets/307601/746a5ba9-b13e-41e9-b3ba-5ec972ee8ccf)

**Comment by usoonees** [comment]
感谢提醒，可以更新到最新版本试试
