### ISSUE TITLE
动图中给出的内容是不是转义有问题？

### ISSUE THREAD

**Issue by sethyuan** [usoonees/logseq-plugin-paste-more#2]
首先，这个插件为摘录内容提供了非常大的便利，为你点赞！👍

关于问题，类似`icon- [optional] A logo`这种内容粘贴进来后会产生额外`\`。

是turndown的问题吗？可以解决吗？

**Comment by usoonees** [comment]
好像是 turndown 的问题，0.1.5 版本fix了一下，现在试试看呢。
https://github.com/mixmark-io/turndown#escaping-markdown-characters
<img width="852" alt="image" src="https://user-images.githubusercontent.com/56818734/168062718-a8140e86-f4d2-4e9a-b874-d9c5658f3a65.png">

**Comment by sethyuan** [comment]
试过了，没问题了。
