### ISSUE TITLE
[Feature Request] 建议处理换行

### ISSUE THREAD

**Issue by sethyuan** [usoonees/logseq-plugin-paste-more#3]
现在的行为是多行内容也都写到同一个block中了，如果能提供选项将不同行的内容写到不同的blocks中就更方便后续处理了。

另外如果能再对标题（#）下面的内容进行自动缩进的话就更完美了。

**Comment by usoonees** [comment]
我也觉得这样更好，正在做这个 feature

**Comment by usoonees** [comment]
试试新版本吧！ @sethyuan
![logseq_paste](https://user-images.githubusercontent.com/56818734/168334539-1d7dc943-639e-40b9-af26-835dc5c6d49f.gif)

**Comment by sethyuan** [comment]
完美！

我有一个插件“Ordered Lists”，可以渲染有序列表，如果能提供一个选项开启对“Ordered Lists”的支持就太好了！

**Comment by usoonees** [comment]
Ordered Lists 插件很赞！感觉单独安装和使用 Ordered Lists 也挺好的。

PS: 感谢你做的 logseq-plugin-luckysheet，让我终于摆脱了 markdown table !
