### ISSUE TITLE
Plugin Freezes Logseq

### ISSUE THREAD

**Issue by dv0zn3r** [usoonees/logseq-plugin-paste-more#4]
Logseq freezes when trying to paste rich text format content from an email client or rtf document. Content is not that big, 10-15 paragraphs with links and images. Mac OS, latest Logseq version, latest plugin version.

**Comment by usoonees** [comment]
I am sorry for the inconvenience. 

You could try pasting them separately or pressing `mod+shift+v` to paste the plain text for temporal solution.

If you meet it again in public websites, please share me the link and I would like to figure out the bottleneck.

**Comment by usoonees** [comment]
Is it normal when paste with plain text? (`mod+shift+v`)
