### ISSUE TITLE
support for google docs paste

### ISSUE THREAD

**Issue by monk-blade** [usoonees/logseq-plugin-paste-more#5]

**Comment by usoonees** [comment]
Doing.

**Comment by monk-blade** [comment]
eagerly waiting. thanks.

**Comment by usoonees** [comment]
Support some simple format in the latest version.

What is the format you are most looking forward to, can you give a link to the document?

**Comment by monk-blade** [comment]
I want multiple list with multiple indentation to paste normally. I will reply after testing new version.

**Comment by usoonees** [comment]
Oh I see, currently not supported, I would try to support this feature.

**Comment by usoonees** [comment]
Try the latest version? Is this what you want?
![May-16-2022 18-42-48](https://user-images.githubusercontent.com/56818734/168576203-0f8035a9-0c24-48e8-a947-f0d7c525d02c.gif)

**Comment by monk-blade** [comment]
🤩🤩🥳
