### ISSUE TITLE
[feature request] 增加从ms excel 拷贝表格的支持

### ISSUE THREAD

**Issue by TweakiOS** [usoonees/logseq-plugin-paste-more#6]
Microsoft office 2019
Logseq 0.75
Windows 10

谢谢你给我们带来很棒的插件，解决了我折腾很久的网页拷贝问题。
还有个需求，望能改善：
从excel里面拷贝过来的表格每个row变成一个block没法组成表格。先拷贝到word里面再拷贝粘贴到logseq是好的。

**Comment by usoonees** [comment]
插件只处理从 web 拷贝的数据，其他(excel & word) 目前都是执行 logseq 的原始粘贴操作。

**Comment by usoonees** [comment]
已添加 excel 粘贴，可以看看最新版本
