### ISSUE TITLE
Feature request: parse indented bullet-point lists

### ISSUE THREAD

**Issue by mrauchs** [usoonees/logseq-plugin-paste-more#7]
Hello,

I've been using this plug-in for 2 weeks and it's been very useful for importing pre-written notes on Apple's Notes app into Logseq – so, first, many thanks for making this available :-) 

As for the feature request: I am using lots of bulleted lists with indenting when taking notes (very similar to how I would do in Logseq with parent, child, and sibling blocks). When using the plug-in to copy-paste the text into Logseq, the indents are unfortunately not parsed and every bullet (point) is at the same level.

It would be very useful if this feature could be implemented as it would save a lot of re-formatting time. 

Many thanks in advance for considering.

Best wishes,
Michel

**Comment by usoonees** [comment]
Fix it in the newest version, give it a try?

**Comment by mrauchs** [comment]
Just tested it and it works perfectly – many thanks for the prompt response and action! Very much appreciate it.
