### ISSUE TITLE
Pasting with code blocks doesn't work correctly

### ISSUE THREAD

**Issue by dmytrodubinin** [usoonees/logseq-plugin-paste-more#9]
I'm trying to insert text from the markdown of a document so that each new line is broken separately, but it doesn't work for me. The insertion is carried out by solid text (the same problem is observed by default in the logseq).
Tried different key combinations but the result is the same. Please check for yourself, maybe I'm doing something wrong.
An example file is attached.
[03-location-map.md](https://github.com/usoonees/logseq-plugin-paste-more/files/10879421/03-location-map.md)

**Comment by usoonees** [comment]
What is the format of the document? Is it plain text or PDF? Please note that this plugin is only capable of handling documents in HTML format when copied (such as Typoral).

![Mar-04-2023 16-59-40](https://user-images.githubusercontent.com/56818734/222886848-b042ef81-adc2-4ab3-838a-19beb08efdea.gif)

**Comment by dmytrodubinin** [comment]
I didn't see in the plugin description that it doesn't work with markdown documents.
Ok then close issue

**Comment by usoonees** [comment]
Sorry, I would add it in description now.

**Comment by usoonees** [comment]
What's more, if you want to split lines, you can try this plugin: https://github.com/hyrijk/logseq-plugin-split-block

> I'm trying to insert text from the markdown of a document so that each new line is broken separately, but it doesn't work for me. The insertion is carried out by solid text (the same problem is observed by default in the logseq). Tried different key combinations but the result is the same. Please check for yourself, maybe I'm doing something wrong. An example file is attached. [03-location-map.md](https://github.com/usoonees/logseq-plugin-paste-more/files/10879421/03-location-map.md)

**Comment by dmytrodubinin** [comment]
> What's more, if you want to split lines, you can try this plugin: https://github.com/hyrijk/logseq-plugin-split-block

Thanks, I opened issue in logseq https://github.com/logseq/logseq/issues/8760 because I found many problems with pasting text from markdown files
